### ISSUE TITLE
Update pip version in  environment_minimal.yml

### ISSUE THREAD

**Issue by antojoseph** [endgameinc/ember#10]
pip 9.0.2 introduced some breaking changes, so it is no longer available on the main channels or conda-forge , Update `- pip=9.0.2=py36_0` to `- pip=9.0.3=py36_0` in environment_minimal.yml

**Comment by mrphilroth** [comment]
I noticed this problem, but I didn't know what the root cause was. Thanks for the info about the breaking changes in 9.0.2. Fixed.

**Comment by ithjz** [comment]
Do you have ready-made compiled toolkits?
