### ISSUE TITLE
How to extract raw feature from a set of PE binaries?

### ISSUE THREAD

**Issue by StarGazerM** [endgameinc/ember#106]
Hi:
    Can I use EMBER to create my own dataset using the binaries collected by myself ? Or maybe can I generate my own raw_feature file using EMBER?

**Comment by gxenos** [comment]
Yes you can, see this file:

https://github.com/elastic/ember/blob/d97a0b523de02f3fe5ea6089d080abacab6ee931/ember/features.py

**Comment by StarGazerM** [comment]
thanks ! I will look into that!

**Comment by nehege** [comment]
> thanks ! I will look into that!

Could you tell me how you make it work for your own dataset?
