### ISSUE TITLE
LIEF error in CentOS/RHEL distributions

### ISSUE THREAD

**Issue by nbeede** [endgameinc/ember#13]
I'm running into an error trying to run Ember on a Cent based distro. It looks like pylief was built using a version of GLIBC that I don't believe is supported on RHEL/CentOS. Has anyone found a workaround or solution to this? I'm able to get it working fine on Ubuntu/Debian, but I need this to run on RHEL because "reasons".

Any help is appreciated!

```Python 2.7.5 (default, Aug  4 2017, 00:39:18)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ember
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ember/__init__.py", line 10, in <module>
    from .features import PEFeatureExtractor
  File "ember/features.py", line 16, in <module>
    import lief
  File "/usr/lib64/python2.7/site-packages/lief/__init__.py", line 4, in <module>
    import _pylief
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib64/python2.7/site-packages/_pylief.so)```

**Comment by ericharley** [comment]
Looks like there was an underlying issue in the LIEF library. The issue below reports the issue and shows that the project resolved it?

https://github.com/lief-project/LIEF/issues/26

**Comment by nbeede** [comment]
Confirmed it works. I was running into problems building it initially because my machine didn't have enough memory for the compilation.
