### ISSUE TITLE
Unable to run scripts/train_ember.py due to lief import error in emberenv

### ISSUE THREAD

**Issue by ArpitaBiswas** [endgameinc/ember#15]
Hello, I'm having lief issues when I train_ember.py inside emberenv. I'm on a CentOS7.5 box.
Lief works fine when I import it from a python interpreter outside of emberenv (screenshot attached). 
![lief outside emberenv](https://user-images.githubusercontent.com/3260021/48289357-01813280-e424-11e8-88d6-102fa86d920d.png)

However, when I the script train_ember.py imports it inside emberenv, it fails to import (screenshot attached) with a GLIBCXX error similar to https://github.com/endgameinc/ember/issues/13.
![lief import in emberenv](https://user-images.githubusercontent.com/3260021/48289616-f2e74b00-e424-11e8-84ee-babfc70508ab.png)

Can someone suggest pointers on how to fix this?

**Comment by comath** [comment]
I don't think I'd be able to reproduce this. Maybe reinstall everything? This looks like the Lief binary can't find the stdlib from the environment.
