### ISSUE TITLE
Optimization of PE extraction

### ISSUE THREAD

**Issue by gauravb3007** [endgameinc/ember#18]
Hello Author,

How can optimization be done on PE files that have more number of imports and exports?

I found that when there are large number of dll and api's in PE files, it takes long time to extract.

Also there are too many for loops in the code, can this be optimised?

**Comment by comath** [comment]
This is likely an issue in the Lief library that's used to parse and extract the raw features that are then vectorized. Updating it breaks compatibility with the current features, though.

**Comment by mrphilroth** [comment]
Version 2 features use a newer version of LIEF that is hopefully more efficient in extracting features  from the samples you're interested in.
