### ISSUE TITLE
create_vectorized_features does not show progress in iPython

### ISSUE THREAD

**Issue by preppie22** [endgameinc/ember#19]
I'm trying to create vectorized features using the instructions given in your Readme.md file. However, I'm unable to see any kind of progress in the interpreter window. There is no way to figure out if there is any activity besides the fact that my CPU is at 100% and the dat files created by the code are being modified.

![code](https://user-images.githubusercontent.com/16285872/53615557-5b546680-3b93-11e9-9c05-1db65a0920e3.png)
![progress](https://user-images.githubusercontent.com/16285872/53615558-5b546680-3b93-11e9-8eb3-68dc704678a1.png)

**Comment by comath** [comment]
I believe this is an issue with [tqdm](https://github.com/tqdm/tqdm). This [line](https://github.com/endgameinc/ember/blob/master/ember/__init__.py#L59) is supposed to produce the progress bar.
