### ISSUE TITLE
Might some code look like incorrect

### ISSUE THREAD

**Issue by PinGMUICT** [endgameinc/ember#2]
In "train_ember.py" script at row number 20, (_"if not (os.path.exists(X_train_path) and os.path.exists(y_train_path))"_). I thinking this one will be used to check the existing path and files of training dataset. In case, the files are existing then it will return true and create vectorized features.

**Might the "not" code in this line be eliminated ?**

Please forgive me if I misunderstand about this.

**Comment by mrphilroth** [comment]
Thanks for your interest in this project! That line simply checks if vectorized features already exist. If they do not exist (hence the "not"), then they need to be calculated. It's an expensive operation and so I don't want to run it if it's already been done.
