### ISSUE TITLE
Unable to install lief == 0.8.3.post3

### ISSUE THREAD

**Issue by pramathesh2** [endgameinc/ember#21]
![Screenshot from 2019-03-28 10-20-04](https://user-images.githubusercontent.com/48665618/55131071-2d872100-5143-11e9-9018-a343dfc40548.png)
Hi,
I am trying to install lief post3 which is needed for training the ember dataset. I am running the command: pip install lief == 0.8.3.post3.
pip is already installed with the latest version in my system. But when I run the command, it only installs lief version 0.8.3 instead of 0.8.3.post3 (as shown in the screenshot).
How to install lief == 0.8.3.post3? or is the command wrong? Please help.
Thanks in advance.

**Comment by ithjz** [comment]
Has it been solved? I also encountered similar mistakes.

**Comment by mrphilroth** [comment]
I'm sorry I didn't respond in a reasonable amount of time. From everything I can tell, this is the right version of LIEF to install. This is what I see in the environment I'm using:
```
>>> import lief
>>> lief.__version__
'0.8.3-18d5b75'
>>>
```

Also, I believe this is the only version of 0.8.3 that pip is able to install.
