### ISSUE TITLE
Feature matrix

### ISSUE THREAD

**Issue by silversurfer147** [endgameinc/ember#22]
Hello, I have one question about features. If I use function read_vectorized_features, I get feature matrix 900 000 x 2351 for X_train. Then I used feature selection SelectKBest from sklearn. I get indexes of columns which should be best, but it is possible to find, what features are in these columns?  For example, I get index 90, is possible to find what type of feature is in this column? I don't know how to do it. Thank you in advance.

**Comment by mrphilroth** [comment]
The feature matrix is laid out in this order:
https://github.com/endgameinc/ember/blob/master/ember/features.py#L481-L490

Feature index 90 is the 90th entry in the `ByteHistogram` feature group. For higher indices, you'll have to subtract the dimensions of the previous feature groups.
