### ISSUE TITLE
providing md5 hash alongwith sha256

### ISSUE THREAD

**Issue by naveennamani** [endgameinc/ember#24]
Can you please a provide a file which maps the sha256 hash of the binary to its md5 hash so that I can easily verify if the provided md5 hashes are available in VirusShare md5 hash list, so that I don't waste time for searching each sha256 hash in virusshare and download it if it is available.

```
Just a json file which looks in the following format is enough
{
    "sha256_1":"md5_1",
    "sha256_2":"md5_2",
    .
    .
    .
}
```

**Comment by mrphilroth** [comment]
Thanks for the suggestion. The md5 hashes are now included in the updated EMBER data releases.

**Comment by mashalzainab** [comment]
Where can I find the md5 hashes? Are they available for the EMBER 2017 dataset?
