### ISSUE TITLE
Hello, are you willing to release the whole kernel as a notebook?

### ISSUE THREAD

**Issue by tee2015** [endgameinc/ember#32]
Hello, is this project still active? I was working on recreating the model without ember function, just wondering if you are willing to release the whole kernel / model as a notebook as I am struggling to successfully import ember to the notebook. the reason to recreate the notebook is because I want to test multiple models and techniques on the dataset

**Comment by mrphilroth** [comment]
Hi. This project is still active. Please make sure you're following the installation instructions in the same Python environment as your notebook before running the notebook. (https://github.com/endgameinc/ember#installation) That way, you should be able to import ember and use those functions. I'm not familiar with any method of releasing the actual kernel that I used to generate the notebook. Also, check out this repository for more examples of what you can do with ember: https://github.com/mrphilroth/camlis-ember-improvements.
