### ISSUE TITLE
How to run Malconv on EMBER?

### ISSUE THREAD

**Issue by GabriellaKwan** [endgameinc/ember#34]
I try to run malconv.py on dataset EMBER. May I ask how to generate a URL to fetch file contents by sha256 hash? What's the data form of 'ember_training.csv.gz' and 'ember_test.csv.gz'  in malconv.py? Thank you in advance.

**Comment by mrphilroth** [comment]
The EMBER dataset on its own does not include the file contents. It only includes the features defined in this repo extracted from the files. So the malconv model cannot be trained with the data distributed here. You will need to gain access to the files on your own or through a third party vendor before you can train the malconv model.
