### ISSUE TITLE
Repeated Warning: [LightGBM] [Warning] No further splits with positive gain, best gain: -inf

### ISSUE THREAD

**Issue by seymour1** [endgameinc/ember#36]
When training the initial LightGBM model from train_ember.py, the above warning message repeats several hundred times, causing a bit of confusion as to whether the model is actually training correctly. The model does seem to train correctly despite the warning.

Looking around, this might be due to hyperparameter choices (decreasing min_data_in_leaf and num_leaves in particular might influence the warning's appearance). There might also be a way to suppress LightGBM's warnings.

Mostly posting this issue so that others running into the same confusion might see it!

**Comment by mrphilroth** [comment]
Thanks @seymour1! I'm going to close this as there's no code changes required. Hopefully others that are running into this will still see it and be reassured.
