### ISSUE TITLE
Where can we get raw binaries for benign files?

### ISSUE THREAD

**Issue by tmw9** [endgameinc/ember#38]
Can you provide the benign binary files you used for feature extraction?

**Comment by gxenos** [comment]
The binaries are not available i think. Try using the sha256 of each sample to reverse search for the executable?

**Comment by Aegon007** [comment]
I am a beginner, I am not quite following: "Try using the sha256 of each sample to reverse search for the executable?", how to do it?

**Comment by jerome-plumecoq** [comment]
Hello,

here : https://www.virustotal.com/gui/home/search

**Comment by tmw9** [comment]
Hey, Thank you all for replying. We required the binary files for a academic project, and requested the files from VirusTotal, they provided it. 
Thanks

**Comment by vietvo89** [comment]
Hello @tmw9, how can you get binary files from Virus Total? I want to have that one for my research project.

Thanks

**Comment by tmw9** [comment]
Hey @vietvo89 , please note that we did not actually get all binaries that were used to generate EMBER dataset.
We requested Virus Total to provide us with some malware binaries for a research project, these binaries may not be the part of EMBER dataset.
You can try to request VirusTotal your requirements, at this [link](https://www.virustotal.com/gui/contact-us/premium-services)
PS: I'm not promoting VirusTotal
