### ISSUE TITLE
Perdiction outputs

### ISSUE THREAD

**Issue by ContegoCode** [endgameinc/ember#42]
So everything appears to be working fine and i do receive an output prediction but my question is which output's are deemed as being malicious and benign

Test One
 7.374090014710014e-08

Test Two
0.9475527058964659

in this case is a higher prediction value indicate the file is benign and any prediction value under 1 is malicious?

thank you in advance.

**Comment by mrphilroth** [comment]
Prediction values are always between zero and one. The very low value you show in test one indicates the file is probably benign and the higher value in test two shows that the file is probably malicious.

**Comment by ContegoCode** [comment]
You are correct the test one is benign but has a value over 1 am I correct? 7.37...... and in test two the file is malicious but has a value of 0.94.... can you elaborate a bit sorry again for the simple question I'm just trying to understand the way files are scored.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by mrphilroth** [comment]
The "e-08" at the end of the first score represents that the number should be multiplied by 10 raised to the -8 power. So it is actually 0.000000000737.
https://en.wikipedia.org/wiki/Scientific_notation#E_notation

**Comment by ContegoCode** [comment]
Omg that makes allot of sense thank you very much!

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________
