### ISSUE TITLE
Unable to run python train_ember.py [/path/to/dataset]

### ISSUE THREAD

**Issue by cngo20** [endgameinc/ember#46]
Hi, 
I get an error each time I try to run python train_ember.py. "usage: train_ember [-h] [-v FEATUREVERSION] [--optimize] DATADIR". 

When I type python train_ember.py /ember2018 (data features folder path), I get this error "is not a directory with raw feature files".

Thanks

**Comment by mrphilroth** [comment]
This is the error message you are getting:
https://github.com/endgameinc/ember/blob/master/scripts/train_ember.py#L19

It appears that the argument `/ember2018` isn't making it into the script. Based on your posted error message, the variable `args.datadir` is empty. Is the directory being escaped somehow before being passed to the script?

**Comment by cngo20** [comment]
Thank you for assistance. I was able to get it to work. However, I am not able to run the classify_binary.py script. Where is the location or which file is the PE binary file?

Thanks!

**Comment by mrphilroth** [comment]
You must provide a PE binary file that you wish to classify. The EMBER data release does not contain one.

**Comment by cngo20** [comment]
Thank you, Phil, for your response.

**Comment by cngo20** [comment]
Hi Phil, 

Do you know where I can find PE Binary files. I have searching throughout the internet but can't find any or at least I don't think I have found them. 

Thanks for you time.

**Comment by mrphilroth** [comment]
Here are some resources available to researchers where you might be able to get data:
https://virusshare.com/
https://www.secrepo.com/
https://github.com/shramos/Awesome-Cybersecurity-Datasets

**Comment by neslgk** [comment]
Hello @cngo20  and @mrphilroth how did you resolve the first error you mentioned above, when you run python train_ember.py? 
I also get:
usage: train_ember [-h] [-v FEATUREVERSION] [--optimize] DATADIR".
is not a directory with raw feature files".

Thanks

**Comment by cngo20** [comment]
Hello,

You need to get and add virus files in order to train the model. I borrowed files from VirusTotal.

I hope this helps.

Best,
Courtenay

Sent from my iPhone

On Mar 18, 2022, at 15:44, neslgk ***@***.***> wrote:

﻿

Hello @cngo20<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcngo20&data=04%7C01%7C%7Ce4ba3f721ae7428ef2dd08da0949fad4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832510603067690%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0qsGuAvKOmAfywPLawptt4eu740NqRTig5%2BfapUIszc%3D&reserved=0> and @mrphilroth<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmrphilroth&data=04%7C01%7C%7Ce4ba3f721ae7428ef2dd08da0949fad4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832510603067690%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zHhBbVoDeEHkG0JK4B%2BMPTvpQmc9c75mQjpyJiNVcN4%3D&reserved=0> how did you resolve the first error you mentioned above, when you run python train_ember.py?
I also get:
usage: train_ember [-h] [-v FEATUREVERSION] [--optimize] DATADIR".
is not a directory with raw feature files".

Thanks

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Felastic%2Fember%2Fissues%2F46%23issuecomment-1072915095&data=04%7C01%7C%7Ce4ba3f721ae7428ef2dd08da0949fad4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832510603067690%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=w0AXjWq8LmxoHbWtdYJk1gxkW7v2FRI0Xf0Uvfw8ZO8%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPHW2XDN3UKYP6FQGGSSMM3VAUWPBANCNFSM4MLOUZEQ&data=04%7C01%7C%7Ce4ba3f721ae7428ef2dd08da0949fad4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832510603067690%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=J2yr%2FcL8Tiu1kzABGdZjTyNA%2FHSyJd2SqKDqkhb0yXg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ce4ba3f721ae7428ef2dd08da0949fad4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832510603067690%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OnIE2YDfzVvtnQc1i2k%2BTw9gA3OG74XLWOYS1d9pYmk%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ce4ba3f721ae7428ef2dd08da0949fad4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832510603067690%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ucikkA8JUxO%2Bz%2FsfTSyXldz73uKcpjv8wosJ8Jnp%2Fpc%3D&reserved=0>.

**Comment by neslgk** [comment]
Hi,

Sure, I thought we needed to train unzipped files from https://ember.elastic.co/ember_dataset_2018_2.tar.bz2
Are you suggesting in stead to only train model borrowed from VirusTotal? We don't need ember dataset at all?

Thanks

**Comment by cngo20** [comment]
You’re correct. You will train from the ember dataset. Check the path to where you’re storing the dataset and make sure it’s the right path in your code.

Sent from my iPhone

On Mar 18, 2022, at 16:01, neslgk ***@***.***> wrote:

﻿

Hi,

Sure, I thought we needed to train unzipped files from https://ember.elastic.co/ember_dataset_2018_2.tar.bz2<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fember.elastic.co%2Fember_dataset_2018_2.tar.bz2&data=04%7C01%7C%7Ccf288603ceaa4dcad1d208da094c6194%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832520912707139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BMqKeS%2Fl9yK6n5Q00MsAtrsWQI61W%2FEYiU%2BXPjWEvJo%3D&reserved=0>
Are you suggesting in stead to only train model borrowed from VirusTotal? We don't need ember dataset at all?

Thanks

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Felastic%2Fember%2Fissues%2F46%23issuecomment-1072918032&data=04%7C01%7C%7Ccf288603ceaa4dcad1d208da094c6194%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832520912707139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BC7qOsM0E8BbnZG9e9lkWTo43VYr5yjK7JICNgqowOY%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPHW2XCETBS2RHDCYMDKCWDVAUYPPANCNFSM4MLOUZEQ&data=04%7C01%7C%7Ccf288603ceaa4dcad1d208da094c6194%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832520912707139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BY4SiXU7pnxMyIVY12xIXmpl8BAL8YUz5a67Ib%2FlftE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ccf288603ceaa4dcad1d208da094c6194%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832520912707139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8FtisDRQqJRP1T0gFzt726bsreQozJ7w4yGVwKTgtzk%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ccf288603ceaa4dcad1d208da094c6194%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832520912707139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FS%2FSo%2FD4NS5b%2F8%2Fvr8eMa97YbPgH6Xl1xp9%2F%2FEZBpBM%3D&reserved=0>.

**Comment by neslgk** [comment]
Ok.
This is how my syntax looks like [I'm using anaconda prompt (anaconda3) on Windows 10]:

python init_ember.py C:\Users\myself\Ember\scripts\ember2018

and I get this error:
usage: train_ember [-h] [-v FEATUREVERSION] [-m] [-t] [--optimize] DATADIR
train_ember: **error: unrecognized arguments**:

Am I missing something here?

Thanks.

**Comment by cngo20** [comment]
I’m not sure but check the syntax documentation for the Windows file path. I don’t think you include C:\.

Sent from my iPhone

On Mar 18, 2022, at 16:12, neslgk ***@***.***> wrote:

﻿

Ok.
This is how my syntax looks like [I'm using anaconda prompt (anaconda3) on Windows 10]:

python init_ember.py C:\Users\myself\Ember\scripts\ember2018

and I get this error:
usage: train_ember [-h] [-v FEATUREVERSION] [-m] [-t] [--optimize] DATADIR
train_ember: error: unrecognized arguments:

Am I missing something here?

Thanks.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Felastic%2Fember%2Fissues%2F46%23issuecomment-1072919662&data=04%7C01%7C%7C9d1b842dd43a413aa4af08da094deef3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832527568222370%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XowlOgDq9R%2BJUcU%2FmV1bWdYl6JTmkgmDh7YBRTAMSzo%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPHW2XGBSLLLNMYNB66C6Z3VAUZZFANCNFSM4MLOUZEQ&data=04%7C01%7C%7C9d1b842dd43a413aa4af08da094deef3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832527568222370%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZGBu5cHeocVKv3RoAsAKasNndGOPZBV6wVamSoEmDXU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C9d1b842dd43a413aa4af08da094deef3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832527568222370%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HcqkxxV98pEKsmOemQkialKEqnT7znoFEopLAVihbZk%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C9d1b842dd43a413aa4af08da094deef3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832527568222370%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=G5kh12vWxSU0MUlj8Te8KQEO%2FUZBTtCkpdagonNVGvc%3D&reserved=0>.

**Comment by neslgk** [comment]
I actually got it.
Thanks a lot Courtenay!

**Comment by cngo20** [comment]
Awesome! You’re welcome.

Sent from my iPhone

On Mar 19, 2022, at 02:57, neslgk ***@***.***> wrote:

﻿

I actually got it.
Thanks a lot Courtenay!

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Felastic%2Fember%2Fissues%2F46%23issuecomment-1073005290&data=04%7C01%7C%7Cc523286412f64076c0c308da09a80162%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832914421480227%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vVymHkLV17tFhSmWM9TiwtNJ3%2Ba3SA7FL8QnXDoP5bU%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPHW2XA3UKVJZV6N2ZEQ5QDVAXFK7ANCNFSM4MLOUZEQ&data=04%7C01%7C%7Cc523286412f64076c0c308da09a80162%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832914421480227%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P1yUD4oOWeczjD%2BjocXHY%2FtD39hqjGUAD1E8MtB412g%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc523286412f64076c0c308da09a80162%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832914421480227%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8tU54pNA3TJdczQoIfS9SOVNNV0%2FHgq0iv2RvBxs%2Bhg%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cc523286412f64076c0c308da09a80162%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637832914421480227%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EP4aOHhv%2B%2BYLeLaH28nNSGm4Gh2ElAz3Rd4YSZXTMRM%3D&reserved=0>.
