### ISSUE TITLE
Cant understand features.py

### ISSUE THREAD

**Issue by gauravb3007** [endgameinc/ember#5]
Hello Phil,

I am doing this project on Malware Detection using Machine Learning, I have a few doubts,

I am not able to understand the class **ByteEntropyHistogram** and how it is working, is there any other easy way out?

Also how to deal with Section properties and Entropy fields?

Please help,
Thank You!

**Comment by drhyrum** [comment]
Please read the reference papers noted at the top ```ember/features.py```.  ByteEntropyHistogram, for example, is explained in more detail here:

https://arxiv.org/pdf/1508.03096.pdf (Saxe and Berlin, 2015)

**Comment by priyanga24** [comment]
hi, i am not able to run the classify_banaries file with the path to model file..whats the issue?
