### ISSUE TITLE
MALCONV on Ember

### ISSUE THREAD

**Issue by priyanga24** [endgameinc/ember#50]
Hi,

How to run ember dataset on Malconv? I want to attempt this competition( https://www.elastic.co/blog/machine-learning-static-evasion-competition). 

So the Malconv model cannot be trained with the data(vectorized dataset) given in your github page? How to gain access to the files?

**Comment by mrphilroth** [comment]
I'm sorry, but we did not provide the resources to run malconv over the EMBER dataset here in this release.
