### ISSUE TITLE
Is the data sequence strictly following with a time series?

### ISSUE THREAD

**Issue by HarrialX** [endgameinc/ember#57]
Hello Dear Author,

I'm curious about the collected data, are they strictly following with a time series? I.e., when using your code to vectorize data into a feature matrix and a corresponding pandas DataFrame, is the previous data always "happens earlier" than the later data? For example, the data in the 0th row must be an event (goodware/malware) earlier than the 1st row.

**Comment by mrphilroth** [comment]
There is a small amount of benign data shared between the two datasets. You can use the sha256 of each sample to deduplicate.

We've provided the month that each sample first appears. Please use that to order the data chronologically. We don't provide any guarantees about the order of samples within the same month.
