### ISSUE TITLE
how to run malconv with ember data

### ISSUE THREAD

**Issue by Aegon007** [endgameinc/ember#59]
I just download the dataset and it is only Json file there, where and how to get raw byte data and run the malconv?

does anybody here can help me?

**Comment by mrphilroth** [comment]
The raw files are not provided in this dataset (https://github.com/endgameinc/ember/issues/38). Other data vendors may be able to help you obtain them. I've heard that [VirusTotal](https://www.virustotal.com/gui/home/search) can provide them for research purposes. Many of the malicious files are available through [VirusShare](https://virusshare.com/).
