### ISSUE TITLE
Lief Requirement

### ISSUE THREAD

**Issue by comath** [endgameinc/ember#7]
Lief's current versions available for anaconda are 0.8.0.post7, 0.8.1.post1, 0.8.2.post1, 0.8.3.post3, 0.9.0, it does not find 0.8.3. Can it be updated to 0.9.0?

**Comment by mrphilroth** [comment]
Unfortunately, after testing, LIEF version 0.9.0 creates different features (both raw and vectorized). So 0.9.0 is bad. I also can't install 0.8.3 in any of my environments. But testing shows that installing 0.8.3.post3 generates the same features. So I updated to the repository to make that the standard.
